// ===================================================================
// PRODUCT TYPES AND THEIR QUALITIES
// This is the single source of truth for all product types and qualities
// ===================================================================

// Display names for product types (used in UI dropdowns)
export const PRODUCT_TYPE_LABELS: Record<string, string> = {
  marble: 'Marble',
  tile: 'Tile',
  magro_stone: 'Magro Stone',
  quartz: 'Quartz',
  terrazzo: 'Terrazzo',
};

// Ordered list of product types for form dropdowns (lowercase keys)
export const PRODUCT_TYPES_ORDERED = [
  'marble',
  'tile',
  'magro_stone',
  'quartz',
  'terrazzo',
] as const;

// Legacy format for analytics charts (capitalized display names)
export const PRODUCT_TYPES = [
  'Marble',
  'Tile',
  'Magro Stone',
  'Quartz',
  'Terrazzo',
] as const;

export type ProductTypeKey = (typeof PRODUCT_TYPES_ORDERED)[number];
export type ProductType = (typeof PRODUCT_TYPES)[number];

// Popular/frequently used qualities by product type (shown at top of dropdown)
export const POPULAR_QUALITIES: Record<ProductTypeKey, string[]> = {
  marble: ['Statuario', 'Michel Angelo', 'Angelo White', 'Royal Crema', 'Ice Berg White'],
  tile: ['Cordoso Beige', 'Art Walnut', 'Terra Beige', 'Concrete Nero', 'Myra Sand'],
  magro_stone: ['Frosty Blanc', 'Cascade'],
  quartz: ['Tajmahal', 'P Grey', 'F Mountain', 'Frosty Bianc'],
  terrazzo: ['I Flower', 'Orbico', 'S Grey', 'R Stone'],
};

// Quality options by product type (lowercase keys for form usage)
export const PRODUCT_QUALITIES_BY_KEY: Record<ProductTypeKey, string[]> = {
  marble: [
    'Antique Beige',
    'Arbescato',
    'Ari Stone White',
    'Beige Granitilo',
    'Beige Serpeggiante',
    'Bianca Lasa',
    'Bianca Marfil',
    'Bianco Fusion',
    'Bianco Michel Angelo',
    'Bianco Scala',
    'Blu O Disuai',
    'Bottichino',
    'Brazilian White',
    'Brescia Aurora',
    'Brescia Marnia',
    'Brescia Onachita',
    'Bronze Amani',
    'Bronze Amani Checks',
    'Bronze Amani Stripes',
    'Calacatta Borgini',
    'Classic Fino',
    'Cappadocia Beige',
    'Caramelo Beige',
    'Carra White',
    'Colorado White',
    'Crème Late',
    'Crème Live',
    'Crème Marfil',
    'Crème Nova',
    'De Martino',
    'Desert Beige',
    'Dover White',
    'Dyna Sardania Beige',
    'El Dorado Beige',
    'Ethiopian Blue',
    'Four Season',
    'Giallo Sienna',
    'Glacier White',
    'Glorious Beige',
    'Golden Dragon',
    'Golden Portoro',
    'Golden Spider',
    'Golden Statuario',
    'Grey Abescato',
    'Gupucci Crème',
    'Iconic Beige',
    'Imperial Beige',
    'Lygorio Beige',
    'Lygorio Crème',
    'Lygorio Grey',
    'Macchia Gold',
    'Macchia Vecchia',
    'Metallica White',
    'Mexican Gold',
    'Michel Angelo',
    'Moon Crème',
    'Moon Light Crema',
    'Omani Beige',
    'Paonazzo',
    'Palissandro',
    'Panda White',
    'Perlato Rosso',
    'Perlato Sicillia',
    'Pink Michel Angelo',
    'Rosalia',
    'Rosso Portugal',
    'Russian Pearl White',
    'Sarren Collin',
    'Santorini Aspro',
    'Sivec White',
    'Statuario',
    'Statuario Toh',
    'Swiss White',
    'Thasos White',
    'Tobacco Brown',
    'Turkey Dyna',
    'Vegas Gold',
    'Venetino',
    'Volakas',
    'White Chiante',
    'White Venezuela',
    'Yellow Valencia',
  ],
  tile: [
    'A Brown',
    'A Gris',
    'A Grigio',
    'Afyon',
    'Alexa Bianco',
    'Alexa Crema',
    'Alexa Gris',
    'Alexa Nero',
    'Amarillo Gold',
    'Antique Beige',
    'AR Naturale',
    'Art Dark Grey',
    'Art Ivory',
    'Art Light Grey',
    'Art Nero',
    'Art Walnut',
    'Avacado',
    'Azure',
    'Barcelona Fossil',
    'Barcelona Grey',
    'Bardiglio Bianco',
    'Basilica Bronze',
    'Basalco Grigio (Full body)',
    'B Apricot (Rustic Finish)',
    'B Dolphin (Rustic Finish)',
    'B Graphite (Rustic Finish)',
    'B Limestone',
    'B Mushroom (Rustic Finish)',
    'Black Slate',
    'Bristal Bronze',
    'C Beige',
    'Calacatta Royal A',
    'Calacutta',
    'Caramel Beige',
    'Cementi Beige',
    'Ceppo',
    'CF Grey',
    'Cleo Travertine',
    'Cold Garno',
    'Concrete',
    'Concrete Nero',
    'Concrete Rust',
    'Cordoso Beige',
    'Cordoso Chiaro',
    'Cordoso Grey',
    'Cordoso Scuro',
    'Cordoso Décor',
    'C Rare',
    'Crema Di Lusso',
    'Culcutta Oro',
    'Dark Garno',
    'Deck Beige',
    'Deck Blast Beige',
    'Deck Blast Brown',
    'Deck Blast Gris',
    'Deck Blast Nero',
    'Deck Grey',
    'Deck Gris',
    'Deck Kota',
    'Deck Rock Grey',
    'Deck Rock Kota',
    'Deck Nero',
    'Deep Ebony',
    'Dior',
    'Dreamy Grey',
    'Earthy Bronze',
    'Earthy Mist',
    'EG Beige',
    'EL Grey',
    'Elite Ash Grey',
    'Elite Black',
    'Elite Dark Grey',
    'Elite Dove Grey',
    'Elite Grey',
    'Elite Ivory',
    'Elite Olive',
    'Elite Peach',
    'Elite Sky',
    'Elite Steel',
    'Elite White',
    'Elite Warm',
    'Era Aqua',
    'EX Grano',
    'Fior Di Pesco',
    'F Jord Canapa',
    'F Jord Grey',
    'F Jord Sugar',
    'Gaillo Atlantide',
    'Granito Carbone (Full body)',
    'Gracile Black',
    'Gracile Crema',
    'Gracile White',
    'G Graphite (Rustic Finish)',
    'G Terrain (Rustic Finish)',
    'Hector Grey',
    'Hualien Grigio',
    'Hualien Jade',
    'I Onyx',
    'Iron Rust',
    'Kotan Bianco',
    'Kotan Crema',
    'Kotan Grigio',
    'L Alba',
    'L Alba Décor',
    'L Argento',
    'L Argento Décor',
    'L Bianco',
    'L Bianco Décor',
    'L Crema',
    'L Crema Décor',
    'L Grigio',
    'L Grigio Décor',
    'L Net',
    'Magic Almond (Plain)',
    'Magic Almond (Rock)',
    'Magic Almond (Sandy)',
    'Magic Bianco (Plain)',
    'Magic Bianco (Rock)',
    'Magic Bianco (Sandy)',
    'Magic Corn Silk (Plain)',
    'Magic Corn Silk (Rock)',
    'Magic Corn Silk (Sandy)',
    'Magic Gold (Plain)',
    'Magic Gold (Rock)',
    'Magic Gold (Sandy)',
    'Magic Gris (Plain)',
    'Magic Gris (Rock)',
    'Magic Gris (Sandy)',
    'Magic Iron (Iron)',
    'Magic Iron (Plain)',
    'Magic Iron (Sandy)',
    'Magic Kota (Plain)',
    'Magic Kota (Rock)',
    'Magic Kota (Sandy)',
    'Magic Mushroom (Plain)',
    'Magic Mushroom (Rock)',
    'Magic Mushroom (Sandy)',
    'Magic Nero (Plain)',
    'Magic Nero (Rock)',
    'Magic Nero (Sandy)',
    'Magic Peach (Plain)',
    'Magic Peach (Rock)',
    'Magic Peach (Sandy)',
    'Magic Terra (Plain)',
    'Magic Terra (Rock)',
    'Magic Terra (Sandy)',
    'Michel A',
    'Midas Argento',
    'Midas Camello',
    'Midas Fumo',
    'Midas Nebbia',
    'Midas Panna',
    'Misty Grey',
    'M Basaltina',
    'Myra Sand',
    'Navona Travertine Almond (Rustic)',
    'Navona Travertine Corn Silk (Rustic)',
    'Navona Travertine Nero (Rustic)',
    'Navona Travertine Peach (Rustic)',
    'Neo Bianco',
    'Neo Burro',
    'Neo Carbone',
    'Neo Chiro',
    'Neo Crema',
    'Neo Gris',
    'Neo Manteca',
    'Neo Moca',
    'Neo Nero',
    'Neo Smoke',
    'Neo Verde',
    'N Statuario',
    'O Grey',
    'Oak Wood Rust',
    'P Bianco',
    'Pacific Gris',
    'Pebble Stone',
    'Perlato Classico',
    'Q Statuario',
    'Q White',
    'R Bianco (Rustic Finish)',
    'Repolano',
    'R Charcoal Black (Rustic Finish)',
    'R Olive (Rustic Finish)',
    'Roccia Deserto',
    'Roccia Grigio',
    'Roccia Lupo',
    'Roccia Pearl',
    'Roccia Sairo',
    'Roccia Stellar',
    'Roman Travertine Corn Silk (Rustic)',
    'Roman Travertine Nero (Rustic)',
    'Roman Travertine Peach (Rustic)',
    'Roman Travertine Silver (Rustic)',
    'R Slate Grey (Rustic Finish)',
    'R Steel Grey (Rustic Finish)',
    'R Tan (Rustic Finish)',
    'S Apricot (Rustic Finish)',
    'Sahara Grey',
    'Sahara Light Grey',
    'Sand Blast Copper',
    'Sand Copper',
    'Sandune Beige',
    'Sandune White',
    'S Beige',
    'Silver Travertine',
    'Slate Bianco',
    'S Graphite (Rustic Finish)',
    'S Dolphin (Rustic Finish)',
    'S Statuario',
    'Stone Deck Beige',
    'Stone Deck Bianco',
    'Stone Deck Brown',
    'Stone Deck Grey',
    'Stone Deck Nero',
    'Statuario A&B (Matt)',
    'Statuario A&B (Polish)',
    'Statuario Naturale A',
    'T Grey',
    'Terra Beige',
    'T Light Grey',
    'T White',
    'Travio Grey',
    'Virtuous White',
    'Warm Garno',
  ],
  magro_stone: [
    'Arctic',
    'Bulgari',
    'Cascade',
    'Castello',
    'Frosty Blanc',
    'Glacier',
    'Graff Gold',
    'Grazia',
    'Kohinoor Gold',
    'Majesty',
    'Smokey',
  ],
  quartz: [
    'A Beige',
    'A Bianco',
    'A Ivory',
    'Alpinous',
    'Amazonite',
    'B Carrara',
    'Blue Beauty Luxe',
    'Cemento',
    'D Brown',
    'E Beige',
    'E White',
    'F Mountain',
    'G Expo',
    'G Mist',
    'Golden Grace',
    'M Concrete',
    'Madona White',
    'Matrostarline',
    'Negril',
    'Nero Tax',
    'P Grey',
    'S Beige',
    'S White',
    'Star Valley',
    'Tajmahal',
  ],
  terrazzo: [
    'Arnico',
    'B Dynamite',
    'B Lasa',
    'B Rose',
    'C Black',
    'Flurry',
    'I Flower',
    'Orbico',
    'R Stone',
    'S Grey',
    'T Grey',
    'Teria',
  ],
};

// Legacy format (capitalized keys) for analytics charts
export const PRODUCT_QUALITIES: Record<ProductType, string[]> = {
  Marble: PRODUCT_QUALITIES_BY_KEY.marble,
  Tile: PRODUCT_QUALITIES_BY_KEY.tile,
  'Magro Stone': PRODUCT_QUALITIES_BY_KEY.magro_stone,
  Quartz: PRODUCT_QUALITIES_BY_KEY.quartz,
  Terrazzo: PRODUCT_QUALITIES_BY_KEY.terrazzo,
};

// Get all qualities as flat array (useful for search)
export function getAllQualities(): string[] {
  return Object.values(PRODUCT_QUALITIES_BY_KEY).flat();
}

// Get qualities for a specific product type (lowercase key)
export function getQualitiesForProductKey(productTypeKey: ProductTypeKey): string[] {
  return PRODUCT_QUALITIES_BY_KEY[productTypeKey] || [];
}

// Get qualities for a specific product type (capitalized name - for analytics)
export function getQualitiesForProduct(productType: ProductType): string[] {
  return PRODUCT_QUALITIES[productType] || [];
}
