// ===================================================================
// PRODUCT TYPES AND THEIR QUALITIES
// This is the single source of truth for all product types and qualities
// ===================================================================

// Display names for OptionsKey values (used in UI)
export const PRODUCT_TYPE_LABELS: Record<string, string> = {
  // Top-level categories
  marble: 'Marble',
  magro: 'Magro',
  // Sub-categories (for detailed display)
  tile: 'Tile',
  stone: 'Stone',
  quartz: 'Quartz',
  terrazzo: 'Terrazzo',
};

// Ordered list for analytics / legacy display
export const PRODUCT_TYPES_ORDERED = [
  'marble',
  'tile',
  'stone',
  'quartz',
  'terrazzo',
] as const;

// Legacy format (capitalized) for analytics charts
export const PRODUCT_TYPES = [
  'Marble',
  'Tile',
  'Stone',
  'Quartz',
  'Terrazzo',
] as const;

export type ProductTypeKey = (typeof PRODUCT_TYPES_ORDERED)[number];
export type ProductType = (typeof PRODUCT_TYPES)[number];

// Popular/frequently used qualities by OptionsKey (shown at top of dropdown).
// IMPORTANT: each string here MUST match an entry in the corresponding
// PRODUCT_QUALITIES_BY_KEY[key] array exactly (including casing), otherwise
// the dropdown won't be able to surface it. The marble entries below were
// re-cased in 2026-06 to match the new inventory list — e.g. 'Angelo White'
// became 'Angelo white' to align with the spreadsheet source of truth.
export const POPULAR_QUALITIES: Record<ProductTypeKey, string[]> = {
  marble: ['Statuario', 'Michel Angelo', 'Angelo white', 'Royal crema', 'Ice berg white'],
  tile: ['Cordoso Beige', 'Art Walnut', 'Terra Beige', 'Concrete Nero', 'Myra Sand'],
  stone: ['Frosty Blanc', 'Cascade'],
  quartz: ['Tajmahal', 'P Grey', 'F Mountain', 'Frosty Bianc'],
  terrazzo: ['I Flower', 'Orbico', 'S Grey', 'R Stone'],
};

// Quality options by OptionsKey (lowercase keys for form usage)
export const PRODUCT_QUALITIES_BY_KEY: Record<ProductTypeKey, string[]> = {
  marble: [
    // 2026-06 inventory sync: this list was replaced verbatim from the
    // updated inventory spreadsheet. Casing, spacing (including the
    // intentional double space in 'Forest  gold'), and ALL-CAPS entries
    // are preserved exactly so they match the SKU register downstream.
    // 312 items.
    'Afyon white',
    'Alexandrita quartzite',
    'Alluminate quartzite',
    'Amalfi grey',
    'Amani brown',
    'Amazonite',
    'Amazonite Extra',
    'Amethyst',
    'Amrone calcite',
    'Ancient green',
    'Angelo white',
    'Aqua green onyx',
    'Aqualight Quartzite',
    'Aquarella golden Quartzite',
    'Arbescato',
    'ARBESCATO VIOLA',
    'Arcipelagus',
    'Ariston white',
    'Atlantis quartzite',
    'Avocado',
    'Azul maccabus',
    'Azul Rose',
    'Azul skyline',
    'Banded agate',
    'Basaltino',
    'Beige travertino',
    'Belgium black',
    'Benofee onyx',
    'Bianca lasa',
    'BIANCO ACROPOLIS',
    'Bianco Anthracite',
    'Bianco Azuli',
    'Bianco covelano',
    'Bianco ibiza',
    'Bianco lasa',
    'Bianco moon face',
    'Bianco olinda',
    'Bianco Palisandro',
    'Bianco reale',
    'Bianco Snow White',
    'Black agate',
    'Black Forest',
    'Black Gold',
    'Black onyx',
    'Black paytham',
    'Blue cristallo',
    'Blue jeans',
    'Blue lazuli',
    'Blue o Disuai',
    'Blue onyx',
    'Blue Patagonia',
    'Bluette veneto',
    'Botanic wave Quartzite',
    'Bottochino',
    'Breche De vendome',
    'Bronze Amani (s)',
    'Bronze amani strips',
    'Bronze spider',
    'Brown portoro',
    'Bulgari Grey',
    'Calacata Fabbricotti',
    'Calacatta cremo fantasy',
    'Calacatta Oro',
    'Calacatta Viola',
    'Calcite blue',
    'California Gold',
    'Candelarius quartzite',
    'Carbon black',
    'Carpet sicilia',
    'Carrara white',
    'Casa blanca',
    'Casa nova',
    'Celadona Quartzite',
    'Ceppo Avorio',
    'Chipolino',
    'Cipolloni Toscanon',
    'Classic pearl',
    'Cola onyx',
    'Colorado white',
    'Copen hegan',
    'Cosmic black',
    'Cosmos 3D',
    'Cosmos 3D pebble',
    'Cream marfil',
    'Crema diva',
    'Crema pearl',
    'Crema siana',
    'Crystal White onyx',
    'Da Vinci quartzite',
    'Dee martino',
    'Diamond black',
    'Diaspro Brecciate',
    'Dior white',
    'Dolce vita',
    'Dorato travertino',
    'Dover white',
    'Emerald quartz',
    'Emotion grey onyx',
    'Eton white',
    'Exotic matrix',
    'Explosion Blue',
    'Exposed concrete',
    'Fabric black',
    'Fabric brown',
    'Fantastico onyx',
    'Ferragamo beige',
    'Fioro di posco',
    'Forest  gold',
    'Francisco',
    'French chiffon',
    'Fusion gold',
    'Fusion quartzite',
    'Fusion wow light',
    'Galaxy coral',
    'Garazia onyx',
    'Giallo gold',
    'Giallo siena',
    'Golden agate',
    'Golden dragon',
    'Golden onyx',
    'Golden portoro-C',
    'Golden portoro-I',
    'Golden Statuario',
    'Greek Chiante',
    'Green fantastico',
    'Green lake',
    'Green lavante',
    'Green onyx',
    'Green sapphire',
    'Green spring',
    'Green volcano',
    'Grego Bronze',
    'Grego Grey',
    'Grego venezia',
    'Grey agate',
    'Grey arbascato',
    'Grey Fito River',
    'Grey flurry',
    'Grey granitilo',
    'Grey Michel Angelo',
    'Grey serpeggiante',
    'Grey Venezuela',
    'Grey William-I',
    'Grey william-T',
    'Grigio Elegant',
    'Gucci crema',
    'Honey onyx',
    'Ice berg grey',
    'Ice berg white',
    'Ijen blue',
    'Illusion',
    'Imperial beige',
    'Infinity grey',
    'Irish Green',
    'Jasper Gold',
    'Jumble agate',
    'K Oro',
    'Labradorite',
    'Lady grey',
    'Lava gold',
    'LEONARDO DA VINCI',
    'Light emperador',
    'Lotus black',
    'Lotus grey',
    'Louise blue',
    'Lygorio beige',
    'Macchia Vecchia',
    'Magic brown',
    'Marine black',
    'Marine blue',
    'Marine green',
    'Matrix',
    'Matrix hydra finish',
    'Maurizio',
    'MAXICAN SPIDER ONYX',
    'Maxican wave',
    'Metal rose',
    'Metal rust',
    'Metallica grey',
    'Metallica white',
    'Mexican gold',
    'Mexican gold onyx',
    'Mexican wave',
    'Michael angelo-p',
    'Michaelangelo FB',
    'Michel Angelo',
    'Michel Angelo -z',
    'Michel angelo-P',
    'Midnight grey',
    'Mirror of sky',
    'Mocha cream',
    'Mocha cream-I',
    'Mocha Granello',
    'Mochachino',
    'Mont black',
    'Monte pulciano',
    'Monte pulciano Venato',
    'Morocco black',
    'Mosic',
    'Nacia Quartz',
    'Nemesis',
    'Nero Antico',
    'Nero fantastico',
    'Nero spider',
    'Nero venato',
    'Nerovecchio',
    'Newton grey',
    'Nior cube',
    'Nior flex',
    'Noche travertino',
    'Nsl black',
    'Nsl gold',
    'ocean black',
    'Ocean wave',
    'Oliva onyx',
    'Olivia onyx',
    'Ondulutu onyx',
    'Ondulutu onyx crosscut',
    'Opera fantastico',
    'Opul white',
    'Ouro pertro Grey',
    'Palissandro gold',
    'Palissandro white',
    'Panda grey',
    'Panda white-B',
    'Panda white-C',
    'Panda white-I',
    'Patagonia',
    'Peter siena',
    'Picasso grey',
    'Pink multicolour onyx',
    'Pink Onyx',
    'Pink velencia',
    'Pink Venezula',
    'Polaris Quartz',
    'Prada white',
    'Premium brown',
    'Qortecia',
    'Rainbow onyx',
    'Red Alicante',
    'Red lavante',
    'Red Picaso classic',
    'Red Travertino',
    'Reno quartzite',
    'Repen Grey',
    'Revolution',
    'Revolution Quartzite',
    'River black',
    'River blue',
    'River grey',
    'Romica grey',
    'Royal beige',
    'Royal crema',
    'Sahara gold',
    'Sandalwood Quartz',
    'Sardinia Beige',
    'Scorpio River',
    'Sea blue',
    'Sequai brown',
    'Shadow storm',
    'Silver portoro',
    'Silver root',
    'Silver strike',
    'Silver travertino',
    'Sky blue',
    'Sky gold',
    'Smokey grey onyx',
    'Smokey onyx',
    'Smokey quartz',
    'Snow white',
    'Sodalite blue',
    'Sonata grey',
    'Spectrus Black',
    'Statuario',
    'Statuario Gold',
    'Statuario moon face',
    'Statuario-N',
    'Statuario-p',
    'Stone wood',
    'Sunset Red',
    'Super lilac',
    'Super White',
    'Supreme black',
    'Swarovski Green panther',
    'Swarovski onyx',
    'Tabacco brown',
    'Temptation blue',
    'Thasos Vein',
    'Thasos white',
    'Tiffany Quartz',
    'Titanium travertino',
    'Tobacco brown',
    'Tobacco brown cross cut',
    'Tropical grey',
    'Valcano',
    'Varde lavante',
    'Vardilio',
    'Verdhe antiogo',
    'Versace Gold',
    'Volcano brown',
    'Volga blue',
    'Walnut FB',
    'Walnut travertino',
    'White chiante',
    'White crystal agate',
    'White crystel onyx',
    'White onyx',
    'White travertino',
    'Yellow Travertino',
    'Ysl',
    'Zebra onyx',
    'Zebra wave onyx',
  ],
  tile: [
    'A Brown',
    'A Gris',
    'A Grigio',
    'Afyon',
    'Alexa Bianco',
    'Alexa Crema',
    'Alexa Gris',
    'Alexa Nero',
    'Amarillo Gold',
    'Antique Beige',
    'AR Naturale',
    'Art Dark Grey',
    'Art Ivory',
    'Art Light Grey',
    'Art Nero',
    'Art Walnut',
    'Avacado',
    'Azure',
    'Barcelona Fossil',
    'Barcelona Grey',
    'Bardiglio Bianco',
    'Basilica Bronze',
    'Basalco Grigio (Full body)',
    'B Apricot (Rustic Finish)',
    'B Dolphin (Rustic Finish)',
    'B Graphite (Rustic Finish)',
    'B Limestone',
    'B Mushroom (Rustic Finish)',
    'Black Slate',
    'Bristal Bronze',
    'C Beige',
    'Calacatta Royal A',
    'Calacutta',
    'Caramel Beige',
    'Cementi Beige',
    'Ceppo',
    'CF Grey',
    'Cleo Travertine',
    'Cold Garno',
    'Concrete',
    'Concrete Nero',
    'Concrete Rust',
    'Cordoso Beige',
    'Cordoso Chiaro',
    'Cordoso Grey',
    'Cordoso Scuro',
    'Cordoso Décor',
    'C Rare',
    'Crema Di Lusso',
    'Culcutta Oro',
    'Dark Garno',
    'Deck Beige',
    'Deck Blast Beige',
    'Deck Blast Brown',
    'Deck Blast Gris',
    'Deck Blast Nero',
    'Deck Grey',
    'Deck Gris',
    'Deck Kota',
    'Deck Rock Grey',
    'Deck Rock Kota',
    'Deck Nero',
    'Deep Ebony',
    'Dior',
    'Dreamy Grey',
    'Earthy Bronze',
    'Earthy Mist',
    'EG Beige',
    'EL Grey',
    'Elite Ash Grey',
    'Elite Black',
    'Elite Dark Grey',
    'Elite Dove Grey',
    'Elite Grey',
    'Elite Ivory',
    'Elite Olive',
    'Elite Peach',
    'Elite Sky',
    'Elite Steel',
    'Elite White',
    'Elite Warm',
    'Era Aqua',
    'EX Grano',
    'Fior Di Pesco',
    'F Jord Canapa',
    'F Jord Grey',
    'F Jord Sugar',
    'Gaillo Atlantide',
    'Granito Carbone (Full body)',
    'Gracile Black',
    'Gracile Crema',
    'Gracile White',
    'G Graphite (Rustic Finish)',
    'G Terrain (Rustic Finish)',
    'Hector Grey',
    'Hualien Grigio',
    'Hualien Jade',
    'I Onyx',
    'Iron Rust',
    'Kotan Bianco',
    'Kotan Crema',
    'Kotan Grigio',
    'L Alba',
    'L Alba Décor',
    'L Argento',
    'L Argento Décor',
    'L Bianco',
    'L Bianco Décor',
    'L Crema',
    'L Crema Décor',
    'L Grigio',
    'L Grigio Décor',
    'L Net',
    'Magic Almond (Plain)',
    'Magic Almond (Rock)',
    'Magic Almond (Sandy)',
    'Magic Bianco (Plain)',
    'Magic Bianco (Rock)',
    'Magic Bianco (Sandy)',
    'Magic Corn Silk (Plain)',
    'Magic Corn Silk (Rock)',
    'Magic Corn Silk (Sandy)',
    'Magic Gold (Plain)',
    'Magic Gold (Rock)',
    'Magic Gold (Sandy)',
    'Magic Gris (Plain)',
    'Magic Gris (Rock)',
    'Magic Gris (Sandy)',
    'Magic Iron (Iron)',
    'Magic Iron (Plain)',
    'Magic Iron (Sandy)',
    'Magic Kota (Plain)',
    'Magic Kota (Rock)',
    'Magic Kota (Sandy)',
    'Magic Mushroom (Plain)',
    'Magic Mushroom (Rock)',
    'Magic Mushroom (Sandy)',
    'Magic Nero (Plain)',
    'Magic Nero (Rock)',
    'Magic Nero (Sandy)',
    'Magic Peach (Plain)',
    'Magic Peach (Rock)',
    'Magic Peach (Sandy)',
    'Magic Terra (Plain)',
    'Magic Terra (Rock)',
    'Magic Terra (Sandy)',
    'Michel A',
    'Midas Argento',
    'Midas Camello',
    'Midas Fumo',
    'Midas Nebbia',
    'Midas Panna',
    'Misty Grey',
    'M Basaltina',
    'Myra Sand',
    'Navona Travertine Almond (Rustic)',
    'Navona Travertine Corn Silk (Rustic)',
    'Navona Travertine Nero (Rustic)',
    'Navona Travertine Peach (Rustic)',
    'Neo Bianco',
    'Neo Burro',
    'Neo Carbone',
    'Neo Chiro',
    'Neo Crema',
    'Neo Gris',
    'Neo Manteca',
    'Neo Moca',
    'Neo Nero',
    'Neo Smoke',
    'Neo Verde',
    'N Statuario',
    'O Grey',
    'Oak Wood Rust',
    'P Bianco',
    'Pacific Gris',
    'Pebble Stone',
    'Perlato Classico',
    'Q Statuario',
    'Q White',
    'R Bianco (Rustic Finish)',
    'Repolano',
    'R Charcoal Black (Rustic Finish)',
    'R Olive (Rustic Finish)',
    'Roccia Deserto',
    'Roccia Grigio',
    'Roccia Lupo',
    'Roccia Pearl',
    'Roccia Sairo',
    'Roccia Stellar',
    'Roman Travertine Corn Silk (Rustic)',
    'Roman Travertine Nero (Rustic)',
    'Roman Travertine Peach (Rustic)',
    'Roman Travertine Silver (Rustic)',
    'R Slate Grey (Rustic Finish)',
    'R Steel Grey (Rustic Finish)',
    'R Tan (Rustic Finish)',
    'S Apricot (Rustic Finish)',
    'Sahara Grey',
    'Sahara Light Grey',
    'Sand Blast Copper',
    'Sand Copper',
    'Sandune Beige',
    'Sandune White',
    'S Beige',
    'Silver Travertine',
    'Slate Bianco',
    'S Graphite (Rustic Finish)',
    'S Dolphin (Rustic Finish)',
    'S Statuario',
    'Stone Deck Beige',
    'Stone Deck Bianco',
    'Stone Deck Brown',
    'Stone Deck Grey',
    'Stone Deck Nero',
    'Statuario A&B (Matt)',
    'Statuario A&B (Polish)',
    'Statuario Naturale A',
    'T Grey',
    'Terra Beige',
    'T Light Grey',
    'T White',
    'Travio Grey',
    'Virtuous White',
    'Warm Garno',
  ],
  stone: [
    'Arctic',
    'Bulgari',
    'Cascade',
    'Castello',
    'Frosty Blanc',
    'Glacier',
    'Graff Gold',
    'Grazia',
    'Kohinoor Gold',
    'Majesty',
    'Smokey',
  ],
  quartz: [
    'A Beige',
    'A Bianco',
    'A Ivory',
    'Alpinous',
    'Amazonite',
    'B Carrara',
    'Blue Beauty Luxe',
    'Cemento',
    'D Brown',
    'E Beige',
    'E White',
    'F Mountain',
    'Frosty Bianc',
    'G Expo',
    'G Mist',
    'Golden Grace',
    'M Concrete',
    'Madona White',
    'Matrostarline',
    'Negril',
    'Nero Tax',
    'P Grey',
    'S Beige',
    'S White',
    'Star Valley',
    'Tajmahal',
  ],
  terrazzo: [
    'Arnico',
    'B Dynamite',
    'B Lasa',
    'B Rose',
    'C Black',
    'Flurry',
    'I Flower',
    'Orbico',
    'R Stone',
    'S Grey',
    'T Grey',
    'Teria',
  ],
};

// Legacy format (capitalized keys) for analytics charts
export const PRODUCT_QUALITIES: Record<ProductType, string[]> = {
  Marble: PRODUCT_QUALITIES_BY_KEY.marble,
  Tile: PRODUCT_QUALITIES_BY_KEY.tile,
  Stone: PRODUCT_QUALITIES_BY_KEY.stone,
  Quartz: PRODUCT_QUALITIES_BY_KEY.quartz,
  Terrazzo: PRODUCT_QUALITIES_BY_KEY.terrazzo,
};

// Get all qualities as flat array (useful for search)
export function getAllQualities(): string[] {
  return Object.values(PRODUCT_QUALITIES_BY_KEY).flat();
}

// Get qualities for a specific OptionsKey (lowercase key)
export function getQualitiesForProductKey(productTypeKey: ProductTypeKey): string[] {
  return PRODUCT_QUALITIES_BY_KEY[productTypeKey] || [];
}

// Get qualities for a specific product type (capitalized name - for analytics)
export function getQualitiesForProduct(productType: ProductType): string[] {
  return PRODUCT_QUALITIES[productType] || [];
}
